default:
  @just --list

build:
  mkdir -p bin
  uv run pyinstaller --onefile --name ptrack_py \
    --paths src --distpath bin src/ptrack_py/__main__.py

test:
  uv run pytest

lint:
  uv run ruff check src
  uv run ty check src

fmt:
  uv run ruff format src
  uv run ruff check --fix-only src
