default:
  @just --list

gen:
  go tool templ generate -path src/internal/gui/views
  go run ./src/cmd/schemagen --dir ..

build: gen
  mkdir -p bin
  go build -o bin/ptrack ./src/cmd/ptrack/

test-unit:
  go test $(go list ./src/... | grep -v 'mockfixture')

test-integration:
  go test -count=1 ./src/internal/mockfixture

test: test-unit test-integration

lint:
  golangci-lint run src/...

fmt:
  gofmt -w src
  go tool templ fmt src/internal/gui/views
